version: 2.1
orbs: #something like dependency
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4 #allows us to use the docker commands
  heroku: circleci/heroku@2.0.0
jobs: #instructions for each step
  build: #build the application, ie installa dependencies
    docker: #container to handle to steps
      - image: cimg/node:16.10
    steps:
      - checkout #copies the working directory of the project
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  build-and-push:
    executor: docker/docker #State the environment that we're going to use, in this casewe let docker decide the defualt
    steps:
      - setup_remote_docker #THis allows us to run docker commands just in case
      - checkout
      - docker/check
      - docker/build:
          image: reginodeang/education-space
          tag: 1.0.1
      - docker/push:
          image: reginodeang/education-space
          tag: 1.0.1

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install #installs heroku cli for our run command
      - checkout
      - run:
          name: Heroku Container Push #the name of the group of commands we are running
          command: heroku container:login
            heroku contrainer:push web -a reginodeang-su-devops
            heroku container:release web -a reginodeang-su-devops

workflows: #defines how each job would run and relate to each toher and any other dependent states
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - build-and-push
