version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0 #3rd part orb of snyk
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: reginodeangjr/education-space
          tag: <<pipeline.git.tag>>
      - docker/push:
          image: reginodeangjr/education-space
          tag: <<pipeline.git.tag>>

  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: reginodeang/education-space #the IMAGE_NAME is a variable we could use in our jobs/steps
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
        # (. = current directory)
        # $IMAGE_NAME gets the value of the IMAGE_NAME from the environment defined above.
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      - build-and-push: #This should run only if a tag is pushed, not if a branch is pushed
          filters:
            tags:
              only: /^v.*/ #only considers tags starting with v (ex. v1.0.2)
            branches:
              ignore: /.*/ #ignores all branches
      - scan:
          requires:
            - build
